// Bounty types and static data

export type BountyStatus = 'open' | 'claimed' | 'submitted' | 'verified' | 'paid';
export type BountyTier = 1 | 2 | 3;

export interface Bounty {
  id: string;
  state: string;
  stateCode: string;
  county: string;
  population: number;
  estimatedCases: number;
  bountyAmountCents: number;
  tier: BountyTier;
  status: BountyStatus;
  notes?: string;
}

// Static seed data — FL priority + major US counties
export const BOUNTIES: Bounty[] = [
  // ─── Florida Tier 1 ───────────────────────────────────────
  {
    id: 'fl-miami-dade',
    state: 'Florida',
    stateCode: 'FL',
    county: 'Miami-Dade',
    population: 2_700_000,
    estimatedCases: 85_000,
    bountyAmountCents: 10_000,
    tier: 1,
    status: 'open',
    notes: 'Online portal at miamidadeclerk.gov/clerk/public-records-requests.page',
  },
  {
    id: 'fl-broward',
    state: 'Florida',
    stateCode: 'FL',
    county: 'Broward',
    population: 1_900_000,
    estimatedCases: 60_000,
    bountyAmountCents: 10_000,
    tier: 1,
    status: 'open',
    notes: 'Also has paid API at browardclerk.org',
  },
  {
    id: 'fl-palm-beach',
    state: 'Florida',
    stateCode: 'FL',
    county: 'Palm Beach',
    population: 1_500_000,
    estimatedCases: 48_000,
    bountyAmountCents: 10_000,
    tier: 1,
    status: 'open',
  },
  {
    id: 'fl-hillsborough',
    state: 'Florida',
    stateCode: 'FL',
    county: 'Hillsborough',
    population: 1_500_000,
    estimatedCases: 50_000,
    bountyAmountCents: 10_000,
    tier: 1,
    status: 'open',
    notes: 'FOIA portal at hillsclerk.justfoia.com',
  },
  {
    id: 'fl-orange',
    state: 'Florida',
    stateCode: 'FL',
    county: 'Orange',
    population: 1_400_000,
    estimatedCases: 44_000,
    bountyAmountCents: 10_000,
    tier: 1,
    status: 'open',
    notes: 'myorangeclerk.com',
  },
  {
    id: 'fl-pinellas',
    state: 'Florida',
    stateCode: 'FL',
    county: 'Pinellas',
    population: 1_000_000,
    estimatedCases: 32_000,
    bountyAmountCents: 7_500,
    tier: 1,
    status: 'open',
  },
  {
    id: 'fl-duval',
    state: 'Florida',
    stateCode: 'FL',
    county: 'Duval',
    population: 1_000_000,
    estimatedCases: 35_000,
    bountyAmountCents: 7_500,
    tier: 1,
    status: 'open',
    notes: 'CORE system searchable; 501 W Adams St, Jacksonville FL 32202',
  },
  {
    id: 'fl-lee',
    state: 'Florida',
    stateCode: 'FL',
    county: 'Lee',
    population: 770_000,
    estimatedCases: 24_000,
    bountyAmountCents: 7_500,
    tier: 1,
    status: 'open',
  },
  {
    id: 'fl-polk',
    state: 'Florida',
    stateCode: 'FL',
    county: 'Polk',
    population: 725_000,
    estimatedCases: 23_000,
    bountyAmountCents: 7_500,
    tier: 1,
    status: 'open',
  },
  {
    id: 'fl-brevard',
    state: 'Florida',
    stateCode: 'FL',
    county: 'Brevard',
    population: 600_000,
    estimatedCases: 19_000,
    bountyAmountCents: 7_500,
    tier: 1,
    status: 'open',
  },
  // ─── Florida Tier 2 ───────────────────────────────────────
  {
    id: 'fl-volusia',
    state: 'Florida',
    stateCode: 'FL',
    county: 'Volusia',
    population: 553_000,
    estimatedCases: 17_000,
    bountyAmountCents: 5_000,
    tier: 2,
    status: 'open',
  },
  {
    id: 'fl-seminole',
    state: 'Florida',
    stateCode: 'FL',
    county: 'Seminole',
    population: 471_000,
    estimatedCases: 14_500,
    bountyAmountCents: 5_000,
    tier: 2,
    status: 'open',
  },
  {
    id: 'fl-sarasota',
    state: 'Florida',
    stateCode: 'FL',
    county: 'Sarasota',
    population: 434_000,
    estimatedCases: 13_000,
    bountyAmountCents: 5_000,
    tier: 2,
    status: 'open',
  },
  {
    id: 'fl-manatee',
    state: 'Florida',
    stateCode: 'FL',
    county: 'Manatee',
    population: 403_000,
    estimatedCases: 12_000,
    bountyAmountCents: 5_000,
    tier: 2,
    status: 'open',
  },
  {
    id: 'fl-collier',
    state: 'Florida',
    stateCode: 'FL',
    county: 'Collier',
    population: 393_000,
    estimatedCases: 11_000,
    bountyAmountCents: 5_000,
    tier: 2,
    status: 'open',
  },
  {
    id: 'fl-osceola',
    state: 'Florida',
    stateCode: 'FL',
    county: 'Osceola',
    population: 388_000,
    estimatedCases: 12_000,
    bountyAmountCents: 5_000,
    tier: 2,
    status: 'open',
  },
  {
    id: 'fl-lake',
    state: 'Florida',
    stateCode: 'FL',
    county: 'Lake',
    population: 383_000,
    estimatedCases: 11_500,
    bountyAmountCents: 5_000,
    tier: 2,
    status: 'open',
  },
  {
    id: 'fl-marion',
    state: 'Florida',
    stateCode: 'FL',
    county: 'Marion',
    population: 382_000,
    estimatedCases: 12_000,
    bountyAmountCents: 5_000,
    tier: 2,
    status: 'open',
  },
  {
    id: 'fl-escambia',
    state: 'Florida',
    stateCode: 'FL',
    county: 'Escambia',
    population: 321_000,
    estimatedCases: 10_500,
    bountyAmountCents: 5_000,
    tier: 2,
    status: 'open',
  },
  {
    id: 'fl-alachua',
    state: 'Florida',
    stateCode: 'FL',
    county: 'Alachua',
    population: 280_000,
    estimatedCases: 9_000,
    bountyAmountCents: 5_000,
    tier: 2,
    status: 'open',
  },
  // ─── Top US Counties (non-FL) — Tier 1 ────────────────────
  {
    id: 'ca-los-angeles',
    state: 'California',
    stateCode: 'CA',
    county: 'Los Angeles',
    population: 10_000_000,
    estimatedCases: 280_000,
    bountyAmountCents: 10_000,
    tier: 1,
    status: 'open',
  },
  {
    id: 'tx-harris',
    state: 'Texas',
    stateCode: 'TX',
    county: 'Harris',
    population: 4_700_000,
    estimatedCases: 160_000,
    bountyAmountCents: 10_000,
    tier: 1,
    status: 'open',
  },
  {
    id: 'az-maricopa',
    state: 'Arizona',
    stateCode: 'AZ',
    county: 'Maricopa',
    population: 4_500_000,
    estimatedCases: 145_000,
    bountyAmountCents: 10_000,
    tier: 1,
    status: 'open',
  },
  {
    id: 'ca-san-diego',
    state: 'California',
    stateCode: 'CA',
    county: 'San Diego',
    population: 3_300_000,
    estimatedCases: 90_000,
    bountyAmountCents: 10_000,
    tier: 1,
    status: 'open',
  },
  {
    id: 'tx-dallas',
    state: 'Texas',
    stateCode: 'TX',
    county: 'Dallas',
    population: 2_600_000,
    estimatedCases: 95_000,
    bountyAmountCents: 10_000,
    tier: 1,
    status: 'open',
  },
  {
    id: 'ny-kings',
    state: 'New York',
    stateCode: 'NY',
    county: 'Kings (Brooklyn)',
    population: 2_500_000,
    estimatedCases: 70_000,
    bountyAmountCents: 10_000,
    tier: 1,
    status: 'open',
  },
  {
    id: 'il-cook',
    state: 'Illinois',
    stateCode: 'IL',
    county: 'Cook',
    population: 5_100_000,
    estimatedCases: 165_000,
    bountyAmountCents: 10_000,
    tier: 1,
    status: 'open',
  },
  {
    id: 'tx-tarrant',
    state: 'Texas',
    stateCode: 'TX',
    county: 'Tarrant',
    population: 2_100_000,
    estimatedCases: 72_000,
    bountyAmountCents: 10_000,
    tier: 1,
    status: 'open',
  },
  {
    id: 'wa-king',
    state: 'Washington',
    stateCode: 'WA',
    county: 'King',
    population: 2_200_000,
    estimatedCases: 65_000,
    bountyAmountCents: 10_000,
    tier: 1,
    status: 'open',
  },
  {
    id: 'ga-fulton',
    state: 'Georgia',
    stateCode: 'GA',
    county: 'Fulton',
    population: 1_100_000,
    estimatedCases: 42_000,
    bountyAmountCents: 7_500,
    tier: 1,
    status: 'open',
  },
  // ─── More US Counties — Tier 2 ────────────────────────────
  {
    id: 'oh-cuyahoga',
    state: 'Ohio',
    stateCode: 'OH',
    county: 'Cuyahoga',
    population: 1_200_000,
    estimatedCases: 40_000,
    bountyAmountCents: 5_000,
    tier: 2,
    status: 'open',
  },
  {
    id: 'pa-philadelphia',
    state: 'Pennsylvania',
    stateCode: 'PA',
    county: 'Philadelphia',
    population: 1_500_000,
    estimatedCases: 55_000,
    bountyAmountCents: 5_000,
    tier: 2,
    status: 'open',
  },
  {
    id: 'nc-mecklenburg',
    state: 'North Carolina',
    stateCode: 'NC',
    county: 'Mecklenburg',
    population: 1_100_000,
    estimatedCases: 38_000,
    bountyAmountCents: 5_000,
    tier: 2,
    status: 'open',
  },
  {
    id: 'mi-wayne',
    state: 'Michigan',
    stateCode: 'MI',
    county: 'Wayne',
    population: 1_700_000,
    estimatedCases: 62_000,
    bountyAmountCents: 5_000,
    tier: 2,
    status: 'open',
  },
  {
    id: 'tn-shelby',
    state: 'Tennessee',
    stateCode: 'TN',
    county: 'Shelby',
    population: 930_000,
    estimatedCases: 35_000,
    bountyAmountCents: 5_000,
    tier: 2,
    status: 'open',
  },
];

export function getBountiesByTier(tier: BountyTier): Bounty[] {
  return BOUNTIES.filter((b) => b.tier === tier);
}

export function getBountyStats() {
  const total = BOUNTIES.length;
  const open = BOUNTIES.filter((b) => b.status === 'open').length;
  const totalPayout = BOUNTIES.reduce((sum, b) => sum + b.bountyAmountCents, 0);
  return { total, open, totalPayout };
}

export function formatBounty(cents: number): string {
  return `$${(cents / 100).toFixed(0)}`;
}

export function formatPopulation(pop: number): string {
  if (pop >= 1_000_000) return `${(pop / 1_000_000).toFixed(1)}M`;
  if (pop >= 1_000) return `${(pop / 1_000).toFixed(0)}K`;
  return pop.toString();
}
