// Master data source — generated by pipeline/pipeline.py
// Run: python pipeline/pipeline.py
import masterJudgesRaw from '../../data/master/state-judges.json';

// ── Types re-exported for convenience ─────────────────────────────────────────

interface MasterStateJudgesData {
  meta?: { generated: string; sources: string[]; totalJudges: number; totalCases: number; pipelineVersion: string };
  generated: string;
  source: string;
  totalJudges: number;
  totalCases: number;
  courtAverage: CourtAverage;
  summary: { judgesLowViolentPrisonRate: number; minViolentPrisonRate: number; maxViolentPrisonRate: number; avgLeniencyScore: number };
  judges: Record<string, StateJudge>;
}

const masterData = masterJudgesRaw as unknown as MasterStateJudgesData;

// Build a synthetic STATE_REGISTRY from master data for backwards compatibility
// Each unique (stateCode, county) pair becomes an entry
const judgesList = Object.values(masterData.judges) as StateJudge[];
const stateCountyPairs = [...new Map(
  judgesList.map(j => [`${j.stateCode}:${j.county}`, { code: j.stateCode, name: j.state, county: j.county }])
).values()];

export interface ViolentCaseStats {
  total: number;
  prisonRate: number;
  probationRate: number;
  jailRate: number;
  prisonCount: number;
  probationCount: number;
}

export interface OffenseStats {
  total: number;
  prison: number;
  probation: number;
  jail: number;
  prisonRate: number;
  probationRate: number;
}

export interface DemographicStats {
  total: number;
  prison: number;
  probation: number;
  prisonRate: number;
  probationRate: number;
}

export interface StateJudge {
  name: string;
  slug: string;
  state: string;
  stateCode: string;
  county: string;
  totalCases: number;
  prisonRate: number;
  jailRate: number;
  probationRate: number;
  otherRate: number;
  prisonCount: number;
  jailCount: number;
  probationCount: number;
  otherCount: number;
  avgCommitmentDays: number | null;
  courtFacility: string;
  leniencyScore: number;
  violentCases: ViolentCaseStats;
  sentenceTypes: Record<string, number>;
  offenseBreakdown: Record<string, OffenseStats>;
  raceBreakdown: Record<string, DemographicStats>;
  genderBreakdown: Record<string, DemographicStats>;
}

export interface CourtAverage {
  prisonRate: number;
  jailRate: number;
  probationRate: number;
  otherRate: number;
  violentCases: ViolentCaseStats;
  avgCommitmentDays: number | null;
}

export interface JudgeProfilesData {
  generated: string;
  source: string;
  totalJudges: number;
  totalCases: number;
  courtAverage: CourtAverage;
  summary: {
    judgesLowViolentPrisonRate: number;
    minViolentPrisonRate: number;
    maxViolentPrisonRate: number;
    avgLeniencyScore: number;
  };
  judges: Record<string, StateJudge>;
}

// ── Build judge cache from master data ────────────────────────────────────────

// All judges from master data (already have stateCode/county set by pipeline)
const allJudgesCache: StateJudge[] = judgesList;

export function getAllStateJudges(): StateJudge[] {
  return allJudgesCache;
}

export function getAvailableStates(): { code: string; name: string; county: string }[] {
  const seen = new Map<string, { code: string; name: string; counties: string[] }>();
  for (const { code, name, county } of stateCountyPairs) {
    if (seen.has(code)) {
      seen.get(code)!.counties.push(county);
    } else {
      seen.set(code, { code, name, counties: [county] });
    }
  }
  return [...seen.values()].map(({ code, name, counties }) => ({
    code,
    name,
    county: counties.length <= 2 ? counties.join(' & ') : `${counties.length} counties`,
  }));
}

export function getStateJudgeBySlug(slug: string): StateJudge | null {
  return allJudgesCache.find(j => j.slug === slug) ?? null;
}

export function getJudgeProfilesMeta(): Omit<JudgeProfilesData, 'judges'> {
  return {
    generated: masterData.generated,
    source: masterData.source,
    totalJudges: masterData.totalJudges,
    totalCases: masterData.totalCases,
    courtAverage: masterData.courtAverage,
    summary: masterData.summary,
  };
}

export function getCourtAverage(): CourtAverage {
  return masterData.courtAverage;
}

export function getLeniencyLabel(score: number): string {
  if (score >= 85) return 'Extremely Lenient';
  if (score >= 70) return 'Very Lenient';
  if (score >= 55) return 'Lenient';
  if (score >= 45) return 'Average';
  if (score >= 30) return 'Strict';
  if (score >= 15) return 'Very Strict';
  return 'Extremely Strict';
}

export function getLeniencyColor(score: number): string {
  if (score >= 85) return '#dc2626'; // bright red
  if (score >= 70) return '#f97316'; // orange-red
  if (score >= 55) return '#f59e0b'; // amber
  if (score >= 45) return '#eab308'; // yellow
  if (score >= 30) return '#84cc16'; // lime
  if (score >= 15) return '#22c55e'; // green
  return '#16a34a'; // dark green
}

export function pct(rate: number): string {
  return `${Math.round(rate * 100)}%`;
}
