// Master data source — generated by pipeline/pipeline.py
// Run: python pipeline/pipeline.py
import masterJudgesRaw from '../../data/master/state-judges.json';

// ── Types re-exported for convenience ─────────────────────────────────────────

interface MasterStateJudgesData {
  meta?: { generated: string; sources: string[]; totalJudges: number; totalCases: number; pipelineVersion: string };
  generated: string;
  source: string;
  totalJudges: number;
  totalCases: number;
  courtAverage: CourtAverage;
  summary: { judgesLowViolentPrisonRate: number; minViolentPrisonRate: number; maxViolentPrisonRate: number; avgLeniencyScore: number };
  judges: Record<string, StateJudge>;
}

const masterData = masterJudgesRaw as unknown as MasterStateJudgesData;

// Build a synthetic STATE_REGISTRY from master data for backwards compatibility
// Each unique (stateCode, county) pair becomes an entry
const judgesList = Object.values(masterData.judges) as StateJudge[];
const stateCountyPairs = [...new Map(
  judgesList.map(j => [`${j.stateCode}:${j.county}`, { code: j.stateCode, name: j.state, county: j.county }])
).values()];

export interface ViolentCaseStats {
  total: number;
  prisonRate: number;
  probationRate: number;
  jailRate: number;
  prisonCount: number;
  probationCount: number;
}

export interface OffenseStats {
  total: number;
  prison: number;
  probation: number;
  jail: number;
  prisonRate: number;
  probationRate: number;
}

export interface DemographicStats {
  total: number;
  prison: number;
  probation: number;
  prisonRate: number;
  probationRate: number;
}

export interface StateJudge {
  name: string;
  slug: string;
  state: string;
  stateCode: string;
  county: string;
  totalCases: number;
  prisonRate: number;
  jailRate: number;
  probationRate: number;
  otherRate: number;
  prisonCount: number;
  jailCount: number;
  probationCount: number;
  otherCount: number;
  avgCommitmentDays: number | null;
  courtFacility: string;
  leniencyScore: number;
  violentCases: ViolentCaseStats;
  sentenceTypes: Record<string, number>;
  offenseBreakdown: Record<string, OffenseStats>;
  raceBreakdown: Record<string, DemographicStats>;
  genderBreakdown: Record<string, DemographicStats>;
}

export interface CourtAverage {
  prisonRate: number;
  jailRate: number;
  probationRate: number;
  otherRate: number;
  violentCases: ViolentCaseStats;
  avgCommitmentDays: number | null;
}

export interface JudgeProfilesData {
  generated: string;
  source: string;
  totalJudges: number;
  totalCases: number;
  courtAverage: CourtAverage;
  summary: {
    judgesLowViolentPrisonRate: number;
    minViolentPrisonRate: number;
    maxViolentPrisonRate: number;
    avgLeniencyScore: number;
  };
  judges: Record<string, StateJudge>;
}

// ── Build judge cache from master data ────────────────────────────────────────

const DEFAULT_VIOLENT_CASES: ViolentCaseStats = {
  total: 0,
  prisonRate: 0,
  probationRate: 0,
  jailRate: 0,
  prisonCount: 0,
  probationCount: 0,
};

// Normalise judges that are missing fields added in later pipeline versions.
function normaliseJudge(j: Partial<StateJudge> & { name: string; slug: string }): StateJudge {
  return {
    state: 'Unknown',
    stateCode: 'UN',
    county: 'Unknown',
    courtFacility: '',
    leniencyScore: 50,
    violentCases: DEFAULT_VIOLENT_CASES,
    sentenceTypes: {},
    offenseBreakdown: {},
    raceBreakdown: {},
    genderBreakdown: {},
    otherRate: 0,
    otherCount: 0,
    avgCommitmentDays: null,
    ...j,
  } as StateJudge;
}

// All judges from master data (already have stateCode/county set by pipeline)
const allJudgesCache: StateJudge[] = judgesList.map(normaliseJudge);

export function getAllStateJudges(): StateJudge[] {
  return allJudgesCache;
}

export function getAvailableStates(): { code: string; name: string; county: string }[] {
  const seen = new Map<string, { code: string; name: string; counties: string[] }>();
  for (const { code, name, county } of stateCountyPairs) {
    if (seen.has(code)) {
      seen.get(code)!.counties.push(county);
    } else {
      seen.set(code, { code, name, counties: [county] });
    }
  }
  return [...seen.values()].map(({ code, name, counties }) => ({
    code,
    name,
    county: counties.length <= 2 ? counties.join(' & ') : `${counties.length} counties`,
  }));
}

export function getStateJudgeBySlug(slug: string): StateJudge | null {
  return allJudgesCache.find(j => j.slug === slug) ?? null;
}

export function getJudgeProfilesMeta(): Omit<JudgeProfilesData, 'judges'> {
  return {
    generated: masterData.generated,
    source: masterData.source,
    totalJudges: masterData.totalJudges,
    totalCases: masterData.totalCases,
    courtAverage: masterData.courtAverage,
    summary: masterData.summary,
  };
}

export function getCourtAverage(): CourtAverage {
  // If the pipeline didn't produce a courtAverage (e.g. IL data skipped),
  // compute a fallback from all judges in the master data.
  const stored = masterData.courtAverage;
  if (stored && typeof stored.prisonRate === 'number') {
    return stored;
  }
  // Compute from all judges
  const judges = allJudgesCache;
  if (judges.length === 0) {
    return {
      prisonRate: 0.25,
      jailRate: 0.30,
      probationRate: 0.40,
      otherRate: 0.05,
      violentCases: { total: 0, prisonRate: 0.50, probationRate: 0.25, jailRate: 0.15, prisonCount: 0, probationCount: 0 },
      avgCommitmentDays: null,
    };
  }
  const totalCases = judges.reduce((s, j) => s + j.totalCases, 0);
  const weightedPrison = judges.reduce((s, j) => s + j.prisonRate * j.totalCases, 0);
  const weightedJail = judges.reduce((s, j) => s + j.jailRate * j.totalCases, 0);
  const weightedProbation = judges.reduce((s, j) => s + j.probationRate * j.totalCases, 0);
  const weightedViolentPrison = judges.reduce((s, j) => s + (j.violentCases?.prisonRate ?? 0) * (j.violentCases?.total ?? 0), 0);
  const weightedViolentProbation = judges.reduce((s, j) => s + (j.violentCases?.probationRate ?? 0) * (j.violentCases?.total ?? 0), 0);
  const totalViolent = judges.reduce((s, j) => s + (j.violentCases?.total ?? 0), 0);
  const prisonRate = totalCases > 0 ? weightedPrison / totalCases : 0.25;
  const jailRate = totalCases > 0 ? weightedJail / totalCases : 0.30;
  const probationRate = totalCases > 0 ? weightedProbation / totalCases : 0.40;
  return {
    prisonRate: Math.round(prisonRate * 10000) / 10000,
    jailRate: Math.round(jailRate * 10000) / 10000,
    probationRate: Math.round(probationRate * 10000) / 10000,
    otherRate: Math.round(Math.max(0, 1 - prisonRate - jailRate - probationRate) * 10000) / 10000,
    violentCases: {
      total: totalViolent,
      prisonRate: totalViolent > 0 ? Math.round(weightedViolentPrison / totalViolent * 10000) / 10000 : 0.5,
      probationRate: totalViolent > 0 ? Math.round(weightedViolentProbation / totalViolent * 10000) / 10000 : 0.25,
      jailRate: 0,
      prisonCount: 0,
      probationCount: 0,
    },
    avgCommitmentDays: null,
  };
}

export function getLeniencyLabel(score: number): string {
  if (score >= 85) return 'Extremely Lenient';
  if (score >= 70) return 'Very Lenient';
  if (score >= 55) return 'Lenient';
  if (score >= 45) return 'Average';
  if (score >= 30) return 'Strict';
  if (score >= 15) return 'Very Strict';
  return 'Extremely Strict';
}

export function getLeniencyColor(score: number): string {
  if (score >= 85) return '#dc2626'; // bright red
  if (score >= 70) return '#f97316'; // orange-red
  if (score >= 55) return '#f59e0b'; // amber
  if (score >= 45) return '#eab308'; // yellow
  if (score >= 30) return '#84cc16'; // lime
  if (score >= 15) return '#22c55e'; // green
  return '#16a34a'; // dark green
}

export function pct(rate: number): string {
  return `${Math.round(rate * 100)}%`;
}
